app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_utilities.scss, app/views/pages/home.html.erb
@thibaudallain @Tanguy75 @sdlgado 
vous pouvez checker ça ?
=> titres et paragraphe

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
Le bouton du form n'est finalement pas fini et en attente d'amélioration avcc simple form
=> form btn done but still have to do simple form

app/assets/stylesheets/components/_form.scss
=> adding a text decoration none to btn submit

app/assets/stylesheets/components/_card-bar.scss, app/assets/stylesheets/config/_utilities.scss, app/views/pages/home.html.erb
car bars done - display + like button @AdelaideEurope @thibaudallain @Tanguy75
=> card bars done

app/controllers/events_controller.rb, app/views/events/new.html.erb, app/views/events/share.html.erb, config/routes.rb, test/controllers/events_controller_test.rb
controller and route for events
=> routes and event controller share new created

app/controllers/events_controller.rb, app/controllers/meetings_controller.rb, app/models/meeting.rb, app/views/meetings/edit.html.erb, app/views/meetings/new.html.erb, app/views/pages/home.html.erb, config/routes.rb, test/controllers/meetings_controller_test.rb
=> routes et controllers

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/config/_colors.scss, app/views/meetings/_attending.html.erb, app/views/meetings/edit.html.erb
=> Button plus tard

app/assets/stylesheets/components/_form.scss, app/controllers/events_controller.rb, app/controllers/meetings_controller.rb, app/models/meeting.rb, app/views/meetings/new.html.erb, config/routes.rb
=> form organisateur ok en back

app/controllers/events_controller.rb, app/controllers/meetings_controller.rb, app/models/meeting.rb, app/views/meetings/_declined.html.erb, app/views/meetings/edit.html.erb, app/views/meetings/new.html.erb
@thibaudallain @Tanguy75 @sdlgado
=> declined ok

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_home-participant.scss, app/controllers/meetings_controller.rb, app/views/meetings/_attending.html.erb, app/views/meetings/_declined.html.erb, app/views/meetings/edit.html.erb, app/views/meetings/new.html.erb
@AdelaideEurope updated views + paths + beacoup
=> updates paths

app/assets/stylesheets/components/_card-participants.scss, app/controllers/meetings_controller.rb, app/views/meetings/show.html.erb, config/routes.rb
=> liste invites 1

app/assets/stylesheets/components/_form.scss, app/controllers/meetings_controller.rb, app/views/meetings/_attending.html.erb, app/views/meetings/index.html.erb, app/views/meetings/new.html.erb
=> list-suite

app/controllers/events_controller.rb, app/views/events/_info_window.html.erb, app/views/events/show.html.erb
=> Event show

app/controllers/meetings_controller.rb, app/views/meetings/_declined.html.erb, app/views/meetings/index.html.erb, app/views/suggested_bars/index.html.erb, db/migrate/20191129104154_add_photo_number_to_meetings.rb, db/schema.rb
@sdlgado @Tanguy75 @thibaudallain
=> Prévenir l'orga + photo invités ne participe pas

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card-participants.scss, app/views/meetings/_attending.html.erb, app/views/meetings/index.html.erb
@AdelaideEurope few scss changes
=> few scss changes

app/assets/stylesheets/components/_card-participants.scss, app/views/meetings/_attending.html.erb, app/views/meetings/index.html.erb
=> last changes cards

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_card-bar.scss, app/assets/stylesheets/components/_card-participants.scss, app/views/events/show.html.erb, app/views/suggested_bars/index.html.erb
@thibaudallain @sdlgado @AdelaideEurope
=> Show event

config/application.rb
=> updated time

app/assets/config/manifest.js, app/assets/javascripts/manifest.json.erb, app/views/layouts/application.html.erb, app/views/shared/_ios_pwa_links.html.erb
@thibaudallain @AdelaideEurope @sdlgado
=> pwa files modified good but still not working on my phone

app/assets/stylesheets/components/_avatar.scss
=> modified margin for link citymapper

app/javascript/components/slidingForm.js, app/views/pages/home.html.erb
=> final arrow

app/assets/stylesheets/components/_card-bar.scss, app/assets/stylesheets/components/_dommage.scss, app/assets/stylesheets/components/_share.scss, app/controllers/events_controller.rb, app/javascript/components/share.js, app/views/meetings/_declined.html.erb, app/views/meetings/new.html.erb, app/views/shared/_waiting_after_vote.html.erb
=> front again

app/assets/stylesheets/config/_utilities.scss, app/javascript/components/slidingInvite.js, app/javascript/packs/application.js, app/views/events/share.html.erb, app/views/meetings/_attending.html.erb, app/views/shared/_waiting_after_vote.html.erb
=> more changes

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_buttons.scss, app/views/events/show.html.erb
=> button has been change with new text

app/javascript/plugins/init_mapbox.js, app/views/events/show.html.erb
=> map markers have been change with image for suggested bars

app/assets/stylesheets/components/_card-bar.scss, app/assets/stylesheets/components/_card-participants.scss
=> marge ok now

app/controllers/events_controller.rb
=> fixing timezone problem in prod using time zone local

app/assets/stylesheets/config/_utilities.scss, app/views/events/show.html.erb
=> button minutes changes

.gitignore, app/assets/stylesheets/components/_card-bar.scss
Carousel suggested bars fixed @AdelaideEurope @thibaudallain
=> carousel fixed

app/views/shared/_waiting_after_vote.html.erb
@AdelaideEurope few last changes
=> few css changes

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_share.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index-meetings.scss, app/javascript/components/btnRecap.js, app/views/events/share.html.erb, app/views/meetings/_recap.html.erb, app/views/meetings/index.html.erb, app/views/shared/_waiting_after_vote.html.erb
=> updates front

app/assets/stylesheets/components/_form.scss
like flash @AdelaideEurope @thibaudallain
=> color form done

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_home-participant.scss, app/assets/stylesheets/components/_loading.scss, app/assets/stylesheets/components/_share.scss, app/views/meetings/_attending.html.erb, app/views/pages/home.html.erb
=> front invités

app/views/suggested_bars/index.html.erb
Salut les amis, si vous voyez ça, c'est parce que j'ai repris notre app et il y avait un probleme dans l'index de la view de suggested_bars.
=> index of suggested bars view fixed: rating.to_i.times..
